kind: Service
apiVersion: v1
metadata:
  name: hej
spec:
  ports:
    - port: 8080
      name: asdf
    - port: 3800
---
kind: Application
apiVersion: argoproj.io/v1alpha1
metadata:
  name: hej
spec:
  destination:
    name: ""
    namespace: ""
    server: ""
  project: ""
---
kind: Namespace
apiVersion: v1
metadata:
  name: hej
spec: {}
