kind: Application
apiVersion: argoproj.io/v1alpha1
metadata: {}
spec:
  destination:
    name: ""
    namespace: ""
    server: ""
  project: ""
---
kind: Service
apiVersion: v1
metadata:
  name: hej
spec:
  ports:
    - port: 123
      name: "hej"
